#ifndef __IAP_LAYOUT_H__
#define __IAP_LAYOUT_H__

#include "../iap_mailbox.h"

#define APROM_BOOTLOADER_START         0x00000000UL
#define APROM_BOOTLOADER_SIZE          0x00010000UL
#define APROM_APPLICATION_START        0x00010000UL
#define APROM_APPLICATION_SIZE         0x00070000UL
#define APROM_APPLICATION_END          (APROM_APPLICATION_START + APROM_APPLICATION_SIZE)
#define APROM_APPLICATION_CRC_ADDR     (APROM_APPLICATION_END - 4UL)
#define APROM_APPLICATION_CRC_SIZE     4UL

#define M261_IAP_SRAM_SIZE             M261_IAP_SRAM_APP_SIZE
#define M261_IAP_SRAM_END              M261_IAP_SRAM_APP_END

#endif /* __IAP_LAYOUT_H__ */
